const assert = require("node:assert/strict");
const { getDashboardHtml } = require("../out/dashboardHtml");

const html = getDashboardHtml("abc123");

assert.match(html, /Codegraph/);
assert.match(html, /Indexed Files/);
assert.match(html, /Search/);
assert.match(html, /Search Workbench/);
assert.match(html, /data-tab="search"/);
assert.match(html, /data-tab="files"/);
assert.match(html, /data-tab="context"/);
assert.match(html, /role="tab"/);
assert.match(html, /aria-selected="true"/);
assert.match(html, /aria-selected="false"/);
assert.match(html, /aria-controls="tab-search"/);
assert.match(html, /role="tabpanel"/);
assert.match(html, /aria-labelledby="tabButton-search"/);
assert.match(html, /Graph Explorer/);
assert.match(html, /kindFilter/);
assert.match(html, /modeFilter/);
assert.match(html, /detailMode/);
assert.match(html, /limitInput/);
assert.match(html, /depthInput/);
assert.match(html, /commandPreview/);
assert.match(html, /command-details/);
assert.match(html, />CLI</);
assert.match(html, /agentQuestion/);
assert.match(html, /selectVisibleResults/);
assert.match(html, /copySelectedLocations/);
assert.match(html, /copyAgentPrompt/);
assert.match(html, /selectionCount/);
assert.match(html, /filePattern/);
assert.match(html, /loadFiles/);
assert.match(html, /resultsPrev/);
assert.match(html, /filesNext/);
assert.match(html, /resultsPageSize/);
assert.match(html, /filesPageSize/);
assert.match(html, /filesJump/);
assert.match(html, /search-workbench/);
assert.match(html, /selectionPanel/);
assert.match(html, /Selected result/);
assert.match(html, /Codegraph Context/);
assert.match(html, /What Context Is For/);
assert.match(html, /Relationship lookup for a selected Codegraph result/);
assert.match(html, /contextActionButtonsHtml/);
assert.match(html, /data-context-mode/);
assert.match(html, /Callers/);
assert.match(html, /Callees/);
assert.match(html, /Impact/);
assert.match(html, /relatedResults/);
assert.match(html, /relationshipSummary/);
assert.match(html, /relationshipSummaries/);
assert.match(html, /relationship-summary/);
assert.match(html, /row-relations/);
assert.match(html, /relationshipActionLabel/);
assert.doesNotMatch(html, /preloadVisibleRelationshipSummaries/);
assert.match(html, /relationshipKey/);
assert.match(html, /selectedResultKeys/);
assert.match(html, /agentPromptText/);
assert.match(html, /Search, inspect, hand off/);
assert.match(html, /Try search: extension/);
assert.match(html, /Open file graph/);
assert.match(html, /absoluteLocation/);
assert.match(html, /data-select-result/);
assert.match(html, /cssEscape/);
assert.match(html, /data-preview/);
assert.match(html, /data-graph/);
assert.match(html, /openGraphForResult/);
assert.match(html, /openGraph/);
assert.match(html, /acquireVsCodeApi/);
assert.match(html, /nonce="abc123"/);
assert.match(html, /type: 'ready'/);
assert.ok(!html.includes("<script nonce=\"bad\""));

const escaped = getDashboardHtml("bad\"&<>");
assert.match(escaped, /bad&quot;&amp;&lt;&gt;/);

console.log("dashboardHtml tests passed");
