const assert = require("node:assert/strict");
const { readFileSync } = require("node:fs");
const { getDashboardScript } = require("../out/dashboardScript");
const { getDashboardStyles } = require("../out/dashboardStyles");

const script = getDashboardScript();
const styles = getDashboardStyles();
const dashboardPanelSource = readFileSync("out/codegraphPanel.js", "utf8");

assert.match(script, /showInlineDetail/);
assert.match(script, /openGraph/);
assert.match(script, /function graphPayload/);
assert.match(script, /source: 'search'/);
assert.match(script, /source: 'files'/);
assert.match(script, /pattern: els\.filePattern\.value\.trim\(\)/);
assert.match(script, /Details/);
assert.match(script, /vscode.postMessage/);
assert.match(script, /relationshipSummary/);
assert.match(script, /cacheKey/);
assert.match(script, /relationshipSummaryContext/);
assert.match(script, /function resetRelationshipSummariesIfContextChanged/);
assert.match(script, /function relationshipSummaryFreshnessKey/);
assert.match(script, /state\.relationshipSummaries = \{\}/);
assert.match(script, /function relationshipKey/);
assert.match(script, /String\(item\.file \|\| item\.path \|\| ''\)/);
assert.match(script, /toLowerCase\(\)/);
assert.match(script, /item\.kind \|\| ''/);
assert.match(script, /\[path, item\.line \|\| '', item\.column \|\| '', item\.kind \|\| '', item\.name \|\| ''\]/);
assert.match(script, /function relationshipBadgesHtml/);
assert.doesNotMatch(script, /function preloadVisibleRelationshipSummaries/);
assert.doesNotMatch(script, /items\.slice\(0, 3\)/);
assert.doesNotMatch(script, /relationshipPreloadBatch/);
assert.match(script, /data-graph-mode/);
assert.match(script, /openGraphForResult\(item, button\.dataset\.graphMode\)/);
assert.match(script, /const graphMode = mode \|\| searchModeForResult\(item\)/);
assert.match(script, /function supportsRelationships/);
assert.match(script, /function searchModeForResult/);
assert.match(script, /const seedKey = item \? relationshipKey\(item\) : query/);
assert.match(script, /source: 'search', seedKey, query/);
assert.match(script, /mode: graphMode/);
assert.match(script, /depth: Number\(els\.depthInput\.value\) \|\| 2/);
assert.match(script, /Graph previews/);
assert.match(script, /List callers/);
assert.match(script, /List callees/);
assert.match(script, /List impact/);
assert.match(script, /graph-cue/);
assert.match(script, /role = item\.action === 'openResult' \? 'option' : 'button'/);
assert.match(script, /aria-selected/);
assert.match(script, /els\.query\.addEventListener\('keydown'/);
assert.match(script, /event\.key === 'ArrowDown' && focusSelectedResult\(\)/);
assert.match(script, /function selectResultRow/);
assert.match(script, /function ensureVisibleResultSelection/);
assert.match(script, /function focusSiblingResultRow/);
assert.match(script, /function focusSelectedResult/);
assert.match(script, /window\.addEventListener\('keydown', handleDashboardShortcut\)/);
assert.match(script, /function handleDashboardShortcut/);
assert.match(script, /function selectedResultItem/);
assert.match(script, /function openSelectedResult/);
assert.match(script, /function graphSelectedResult/);
assert.match(script, /key === 'enter' && openSelectedResult\(\)/);
assert.match(script, /key === 'g' && graphSelectedResult\(\)/);
assert.match(script, /state\.visibleResults = page\.items/);
assert.match(script, /state\.visibleResults \|\| \[\]/);
assert.match(script, /function isInteractiveTarget/);
assert.match(script, /const savedState = vscode\.getState && vscode\.getState\(\)/);
assert.match(script, /savedState && savedState\.dashboard/);
assert.match(script, /function restoreDashboardInputs/);
assert.match(script, /function persistDashboardState/);
assert.match(script, /searchRequestId/);
assert.match(script, /filesRequestId/);
assert.match(script, /relatedRequestId/);
assert.match(script, /if \(message\.requestId && message\.requestId !== state\.searchRequestId\) \{ return; \}/);
assert.match(script, /if \(message\.requestId && message\.requestId !== state\.filesRequestId\) \{ return; \}/);
assert.match(script, /if \(message\.requestId && message\.requestId !== state\.relatedRequestId\) \{ return; \}/);
assert.match(script, /vscode\.setState\(\{[\s\S]*dashboard:/);
assert.match(script, /state\.selectedResultKey = relationshipKey\(item\)/);
assert.match(script, /items\.find\(\(item\) => relationshipKey\(item\) === selectedKey\)/);
assert.match(script, /activeTab: state\.activeTab/);
assert.match(script, /inputs,/);
assert.match(script, /event\.key === 'ArrowDown' \|\| event\.key === 'ArrowUp'/);
assert.match(script, /renderResults\('first'\)/);
assert.match(script, /renderResults\('last'\)/);
assert.match(script, /ensureVisibleResultSelection\(page\.items, selectionHint\)/);
assert.match(script, /hint === 'last' \? items\[items\.length - 1\] : items\[0\]/);
assert.match(script, /nextIndex >= rows\.length && state\.resultPage < Math\.ceil/);
assert.match(script, /nextIndex < 0 && state\.resultPage > 1/);
assert.match(script, /event\.key === 'Enter'[\s\S]*vscode\.postMessage\(\{ type: action, item: item\(\) \}\)/);
assert.match(script, /isInteractiveTarget\(event\.target\) && event\.target !== row/);
assert.doesNotMatch(script, /data-related/);

assert.match(styles, /\.inline-detail/);
assert.match(styles, /\.detail-grid/);
assert.match(styles, /\.action-tab/);
assert.match(styles, /\.search-workbench/);
assert.match(styles, /grid-template-columns: minmax\(0, 1fr\) minmax\(220px, min\(32vw, 380px\)\)/);
assert.match(styles, /section\.tab-panel[\s\S]*container-type: inline-size/);
assert.match(styles, /@container \(max-width: 900px\)[\s\S]*\.search-inspector/);
assert.match(styles, /\.search-inspector[\s\S]*container-type: inline-size/);
assert.match(styles, /@container \(max-width: 320px\)[\s\S]*\.relationship-group \{ grid-template-columns: 1fr; \}/);
assert.match(styles, /@container \(max-width: 320px\)[\s\S]*\.graph-cue \{ display: none; \}/);
assert.match(styles, /\.row-title[\s\S]*-webkit-line-clamp: 2/);
assert.match(styles, /\.row-detail[\s\S]*overflow-wrap: anywhere/);
assert.match(styles, /\.detail-grid strong[\s\S]*white-space: normal/);
assert.match(script, /title="' \+ escapeHtml\(label\) \+ '"/);
assert.match(styles, /\.results-pane[\s\S]*min-height: 0/);
assert.match(styles, /\.search-inspector/);
assert.match(styles, /\.row-relations/);
assert.match(styles, /min-height: 18px/);
assert.match(styles, /\.relationship-summary/);
assert.match(styles, /\.relationship-group:hover/);
assert.match(styles, /\.relationship-group:focus-visible/);
assert.match(styles, /\.graph-cue/);
assert.match(styles, /\.command-details/);
assert.match(styles, /\.command-details summary/);
assert.match(styles, /@media \(max-width: 820px\)[\s\S]*\.search-workbench \{ grid-template-columns: 1fr; \}/);
assert.match(styles, /@media \(max-width: 560px\)[\s\S]*\.search-box,[\s\S]*\.head-tools,[\s\S]*\.option-grid \{ grid-template-columns: 1fr; \}/);

assert.match(dashboardPanelSource, /function showCodegraphDocument/);
assert.match(dashboardPanelSource, /viewColumn: vscode\.ViewColumn\.Beside/);
assert.match(dashboardPanelSource, /searchRequestId/);
assert.match(dashboardPanelSource, /filesRequestId/);
assert.match(dashboardPanelSource, /relatedRequestId/);
assert.match(dashboardPanelSource, /requestId !== this\.searchRequestId/);
assert.match(dashboardPanelSource, /requestId !== this\.filesRequestId/);
assert.match(dashboardPanelSource, /requestId !== this\.relatedRequestId/);

console.log("dashboardAssets tests passed");
