const assert = require("node:assert/strict");
const { readFileSync } = require("node:fs");
const { getGraphHtml } = require("../out/graphHtml");

const html = getGraphHtml("abc123");
const graphHtmlSource = readFileSync("out/graphHtml.js", "utf8");

assert.match(html, /Graph Explorer/);
assert.match(html, /title-row/);
assert.match(html, /topbar-meta/);
assert.match(html, /indexFreshness/);
assert.match(html, /Index unknown/);
assert.match(html, /graphActivity/);
assert.match(html, /refreshGraphActivity/);
assert.match(html, /toggleControls/);
assert.match(html, /toggleDetailsTop/);
assert.match(html, /Hide graph controls/);
assert.match(html, /activityPanel/);
assert.match(html, /activityList/);
assert.match(html, /Graph activity/);
assert.match(html, /Refresh graph data/);
assert.match(html, /graph-icon/);
assert.match(html, /graphNetwork/);
assert.match(html, /state-card loading/);
assert.match(html, /Loading Graph Explorer/);
assert.match(html, /Reading Codegraph workspace state/);
assert.match(html, /graphInsight/);
assert.match(html, /Render a graph to see structure hints/);
assert.match(html, /miniMap/);
assert.match(html, /clusterOverlay/);
assert.match(html, /resetView/);
assert.match(html, /stepLimitDown/);
assert.match(html, /fitView/);
assert.match(html, /toggleMotion/);
assert.match(html, /toggleOrbit/);
assert.match(html, /toggleFocus/);
assert.match(html, /clearFocus/);
assert.match(html, /toggleDetails/);
assert.match(html, /toggleLegend/);
assert.match(html, /toggleMiniMap/);
assert.match(html, /toggleClusters/);
assert.match(html, /exportPng/);
assert.match(html, /exportJson/);
assert.match(html, /copyMarkdown/);
assert.match(html, /depthMode/);
assert.match(html, /spacingMode/);
assert.match(html, /labelMode/);
assert.match(html, /filePattern/);
assert.match(html, /icon-actions/);
assert.match(html, /quick-selects/);
assert.match(html, /action-menu/);
assert.match(html, /viewActions/);
assert.match(html, /exportActions/);
assert.match(html, /View actions/);
assert.match(html, /Export and copy/);
assert.match(html, />Reset view</);
assert.match(html, />Fewer nodes</);
assert.match(html, /menu-action/);
assert.match(html, /toggleHelp/);
assert.match(html, /shortcutOverlay/);
assert.match(html, /Shortcuts & gestures/);
assert.match(html, /Focus search/);
assert.match(html, /advanced-controls/);
assert.match(html, /advancedControls/);
assert.match(html, /advanced-panel/);
assert.match(html, /Graph options/);
assert.match(html, /Show details/);
assert.match(html, /Show legend/);
assert.match(html, /Show minimap/);
assert.match(html, /Hide cluster regions/);
assert.match(html, /Export PNG/);
assert.match(html, /Export graph JSON/);
assert.match(html, /Copy graph summary as Markdown/);
assert.match(html, /graphStats/);
assert.match(html, /graphModeBar/);
assert.match(html, /hoverTip/);
assert.match(html, /Start motion/);
assert.match(html, /Start orbit/);
assert.match(html, />Motion</);
assert.match(html, />Markdown</);
assert.match(html, />Shortcuts</);
assert.match(html, /Focus only/);
assert.match(html, /seedKey/);
assert.match(html, /Deep space/);
assert.match(html, /Balanced spacing/);
assert.match(html, /Focus labels/);
assert.match(html, /File pattern/);
assert.match(html, /Search graph/);
assert.match(html, /File structure/);
assert.match(html, /Radial/);
assert.match(html, /Flow/);
assert.match(html, /Layered/);
assert.match(html, /Bundle/);
assert.match(html, /Spread/);
assert.match(html, /20 nodes/);
assert.match(html, /<option value="80" selected>80 nodes<\/option>/);
assert.doesNotMatch(html, /<option value="20" selected>/);
assert.match(html, /nonce="abc123"/);
assert.match(html, /vis-network/);
assert.match(html, /new vis\.Network/);
assert.match(graphHtmlSource, /function escapeScriptContent/);
assert.ok(graphHtmlSource.includes("<\\\\/script"));
assert.equal((html.match(/<script nonce=/g) || []).length, 2);
assert.equal((html.match(/<\/script>/g) || []).length, 2);
assert.doesNotMatch(html, /<\/script[^>]*>[\s\S]*<\/script[^>]*>[\s\S]*<\/script/i);
assert.match(html, /acquireVsCodeApi/);
assert.match(html, /type: 'ready'/);
assert.ok(!html.includes("<script nonce=\"bad\""));

const escaped = getGraphHtml("bad\"&<>");
assert.match(escaped, /bad&quot;&amp;&lt;&gt;/);

console.log("graphHtml tests passed");
