const assert = require("node:assert/strict");
const { readFileSync } = require("node:fs");
const { getGraphScript } = require("../out/graphScript");
const { getGraphStyles } = require("../out/graphStyles");

const script = getGraphScript();
const styles = getGraphStyles();
const graphPanelSource = readFileSync("out/codegraphGraphPanel.js", "utf8");

assert.match(script, /function buildGraph/);
assert.match(script, /function renderGraphNow/);
assert.match(script, /function showLoading/);
assert.match(script, /function graphStateCardHtml/);
assert.match(script, /function emptyStateTitle/);
assert.match(script, /function emptyStateActions/);
assert.match(script, /function handleStateAction/);
assert.match(script, /function clearGraphFilters/);
assert.match(script, /data-state-action/);
assert.match(script, /Number\(els\.limit\.value\) \|\| 80/);
assert.match(script, /requestAnimationFrame\(\(\) => renderGraphNow\(revision\)\)/);
assert.match(script, /message\.type === 'loading'/);
assert.match(script, /activeGraphRequestId/);
assert.match(script, /function acceptGraphMessage/);
assert.match(script, /function acceptExpansionMessage/);
assert.match(script, /requestId < state\.activeGraphRequestId/);
assert.match(script, /requestId === state\.activeGraphRequestId/);
assert.match(script, /Using cached indexed files/);
assert.match(script, /Using cached graph results/);
assert.match(script, /function recordActivity/);
assert.match(script, /function renderActivity/);
assert.match(script, /function renderActivityList/);
assert.match(script, /function setActivityOpen/);
assert.match(script, /function updateIndexFreshness/);
assert.match(script, /function relativeTime/);
assert.match(script, /state\.indexUpdatedAt = Number\(message\.indexUpdatedAt\) \|\| 0/);
assert.match(script, /message\.type === 'indexChanged'/);
assert.match(script, /Codegraph index changed \| cache cleared/);
assert.match(script, /function refreshCurrentGraph/);
assert.match(script, /function graphRequestLabel/);
assert.match(script, /graphActivity\.addEventListener\('click'/);
assert.match(script, /refreshGraphActivity\.addEventListener\('click', refreshCurrentGraph\)/);
assert.match(script, /refreshActivityPanel\.addEventListener\('click', refreshCurrentGraph\)/);
assert.match(script, /force: Boolean\(force\)/);
assert.match(script, /requestGraphData\(false, true\)/);
assert.match(script, /Cached' : 'Loaded'/);
assert.match(script, /Expanded ' \+ message\.mode/);
assert.match(script, /function buildRelationshipGraph/);
assert.match(script, /els\.mode\.value === 'callers' \|\| els\.mode\.value === 'callees' \|\| els\.mode\.value === 'impact'/);
assert.match(script, /function buildSearchFileGraph/);
assert.match(script, /matchType = els\.mode\.value === 'text'/);
assert.match(script, /mode === 'callers'/);
assert.match(script, /addEdge\(symbol, root, mode, true\)/);
assert.match(script, /addEdge\(root, symbol, mode, true\)/);
assert.match(script, /secondary: true/);
assert.match(script, /addEdge\(symbol, file, 'defined in', false, true\)/);
assert.match(script, /function addOmittedNode/);
assert.match(script, /hidden by the graph limit/);
assert.match(script, /addOmittedNode\(root, files\.length - rendered\.length, 'files'/);
assert.match(script, /addOmittedNode\(root, results\.length - rendered\.length, 'results'/);
assert.match(script, /addOmittedNode\(root, results\.length - rendered\.length, mode/);
assert.match(script, /function expandGraphLimit/);
assert.match(script, /function collapseGraphLimit/);
assert.match(script, /function nextLimitValue/);
assert.match(script, /function previousLimitValue/);
assert.match(script, /function showMoreLabel/);
assert.match(script, /id="showLess"/);
assert.match(script, /id="showMore"/);
assert.match(script, /showLessButton\.addEventListener\('click', collapseGraphLimit\)/);
assert.match(script, /showMoreButton\.addEventListener\('click', \(\) => expandGraphLimit\(node\)\)/);
assert.match(script, /id="showAll"/);
assert.match(script, /showAllButton\.addEventListener\('click', \(\) => expandGraphLimit\(node, true\)\)/);
assert.match(script, /const canStepLimit = raw\.omitted && nextLimitValue\(currentLimit\) > currentLimit/);
assert.match(script, /const canStepDown = previousLimitValue\(currentLimit\) < currentLimit/);
assert.match(script, /canStepLimit \? '' : 'disabled'/);
assert.match(script, /function graphTotalLimit/);
assert.match(script, /function ensureLimitOption/);
assert.match(script, /state\.previousLimitBeforeAll = current/);
assert.match(script, /setSelectValue\(els\.limit, String\(next\)\)/);
assert.match(script, /state\.motion = false/);
assert.match(script, /els\.labelMode\.value = 'minimal'/);
assert.match(script, /node && node\.raw && node\.raw\.omitted[\s\S]*expandGraphLimit\(node\)/);
assert.match(script, /ensureLimitOption\(next\)/);
assert.match(script, /setSelectValue\(els\.limit, String\(next\)\)/);
assert.match(script, /els\.source\.value === 'files'[\s\S]*render\(\)[\s\S]*requestGraphData\(\)/);
assert.match(script, /Show more up to/);
assert.match(script, /omitted: Math\.max\(files\.length - rendered\.length, 0\)/);
assert.match(script, /omitted: Math\.max\(results\.length - rendered\.length, 0\)/);
assert.match(script, /arrows: \{ to: \{ enabled: Boolean\(edge\.directed\)/);
assert.match(script, /function secondaryColors/);
assert.match(script, /state\.hubIds = new Set\(topConnectedNodes\(graph, 4\)/);
assert.match(script, /const hub = state\.hubIds && state\.hubIds\.has\(node\.id\)/);
assert.match(script, /node\.type === 'more' \? 16/);
assert.match(script, /readableNodeColor/);
assert.match(script, /parseCssColor/);
assert.match(script, /size: hub && node\.type !== 'root' \? baseSize \+ 3 : baseSize/);
assert.match(script, /width: edge\.secondary \? 0\.7 : edge\.directed \? 1\.35 : 1\.1/);
assert.match(script, /const secondary = Boolean\(node\.raw && node\.raw\.secondary\)/);
assert.match(script, /state\.hubIds && state\.hubIds\.has\(node\.id\)/);
assert.match(script, /if \(secondary && !focused\) \{ return true; \}/);
assert.match(script, /node\.raw && node\.raw\.omitted/);
assert.match(script, /type === 'more'/);
assert.match(script, /state\.theme\.warning/);
assert.match(script, /--vscode-editorWarning-foreground/);
assert.match(script, /function graphSummaryText/);
assert.match(script, /function renderGraphInsight/);
assert.match(script, /function graphModeTitle/);
assert.match(script, /function nodeTypeCounts/);
assert.match(script, /function topConnectedNodes/);
assert.match(script, /class="insight-chip/);
assert.match(script, /function viewStateActions/);
assert.match(script, /data-view-action/);
assert.match(script, /show-full-graph/);
assert.match(script, /clear-focus/);
assert.match(script, /show-more/);
assert.match(script, /function handleViewAction/);
assert.match(script, /rendered\.toLocaleString\(\) \+ '\/' \+ graph\.total\.toLocaleString\(\) \+ ' rendered'/);
assert.match(script, /function graphOmissionText/);
assert.match(script, /hidden by limit/);
assert.match(script, /new vis\.Network/);
assert.match(script, /new vis\.DataSet/);
assert.match(script, /function isVisNetworkReady/);
assert.match(script, /function applyInitialGraph/);
assert.match(script, /initialGraphApplied/);
assert.match(script, /initialGraphKey/);
assert.match(script, /function graphSeedKey/);
assert.match(script, /seed\.seedKey \|\| ''/);
assert.match(script, /state\.initialGraphApplied && state\.initialGraphKey === seedKey/);
assert.match(script, /state\.initialGraphKey = seedKey/);
assert.match(script, /resetSelection\(\)/);
assert.match(script, /function announceGraphSeed/);
assert.match(script, /Loading ' \+ trimLabel\(label, 46\)/);
assert.match(script, /Switching graph context/);
assert.match(script, /if \(seed\.mode\) \{ setSelectValue\(els\.mode, seed\.mode\); \}/);
assert.match(script, /function setSelectValue/);
assert.match(script, /Graph renderer failed to load/);
assert.match(script, /typeof vis !== 'undefined'/);
assert.match(script, /function networkOptions/);
assert.match(script, /function physicsOptions/);
assert.match(script, /function graphComplexity/);
assert.match(script, /function stabilizationIterations/);
assert.match(script, /function stabilizationUpdateInterval/);
assert.match(script, /complexity > 450[\s\S]*return 80/);
assert.match(script, /complexity > 260[\s\S]*return 120/);
assert.match(script, /iterations: stabilizationIterations\(\)/);
assert.match(script, /updateInterval: stabilizationUpdateInterval\(\)/);
assert.match(script, /function layoutOptions/);
assert.match(script, /els\.layout\.value === 'flow'/);
assert.match(script, /function smoothOptions/);
assert.match(script, /function updateNetworkOptions/);
assert.match(script, /function renderMiniMap/);
assert.match(script, /function renderClusterOverlay/);
assert.match(script, /function scheduleClusterOverlayRender/);
assert.match(script, /state\.clusterOverlayOpen/);
assert.match(script, /clusterOverlayFrame/);
assert.match(script, /clusterOverlayForce/);
assert.match(script, /activeClusterKey/);
assert.match(script, /function selectCluster/);
assert.match(script, /function clearClusterFilter/);
assert.match(script, /function showClusterDetails/);
assert.match(script, /Inside group/);
assert.match(script, /prevClusterNodes/);
assert.match(script, /nextClusterNodes/);
assert.match(script, /function nodeTypeRank/);
assert.match(script, /function pauseGraphMotionForCluster/);
assert.match(script, /stopPropagation/);
assert.match(script, /Show only this group/);
assert.match(script, /id="showOnlyGroup"/);
assert.match(script, /id="showClusterList"/);
assert.match(script, /Group list/);
assert.doesNotMatch(script, /state\.activeClusterKey === key\) \{\s*clearClusterFilter\(\)/);
assert.match(script, /pauseGraphMotionForCluster\(\)/);
assert.match(script, /id="showFullGraph"/);
assert.match(script, /Show full graph/);
assert.match(script, /function clusterNodeMatches/);
assert.match(script, /function isNodeHiddenByCluster/);
assert.match(script, /function isEdgeHiddenByCluster/);
assert.match(script, /data-cluster-key/);
assert.match(script, /attachClusterOverlayHandlers/);
assert.match(script, /function clusterKeyForNode/);
assert.match(script, /function flowPaletteColor/);
assert.match(script, /function flowPaletteKey/);
assert.match(script, /canvasToDOM/);
assert.match(script, /class="cluster-hull' \+ \(active \? ' active' : ''\)/);
assert.match(script, /class="cluster-fill"/);
assert.match(script, /class="cluster-label"/);
assert.match(script, /state\.theme\.flowCyan/);
assert.match(script, /function computeFocus/);
assert.match(script, /function selectNode/);
assert.match(script, /function connectedNodes/);
assert.match(script, /function mergeVirtualFileNeighbors/);
assert.match(script, /function fileChildrenForDirectory/);
assert.match(script, /not rendered/);
assert.match(script, /function canExpandNode/);
assert.match(script, /const expandableRoot = node && node\.type === 'root' && Boolean\(raw\.name \|\| raw\.mode\)/);
assert.match(script, /function expansionQueryFor/);
assert.match(script, /function expandFromNode/);
assert.match(script, /function mergeExpandedNode/);
assert.match(script, /function mergeExpansionResult/);
assert.match(script, /function ensureGraphNode/);
assert.match(script, /function ensureGraphEdge/);
assert.match(script, /function refreshGraphDataSets/);
assert.match(script, /type: 'expandNode', query, mode: graphMode, sourceId: node\.id, graphRequestId: state\.activeGraphRequestId/);
assert.match(script, /message\.type === 'expandedNode'[\s\S]*acceptExpansionMessage\(message\)/);
assert.match(script, /state\.expandedCount = 0/);
assert.match(script, /state\.graph\.expanded = state\.expandedCount/);
assert.match(script, /expanded: state\.graph\.expanded \|\| state\.expandedCount \|\| 0/);
assert.match(script, /nodes added by exploration/);
assert.match(script, /graph\.expanded \? graph\.expanded\.toLocaleString\(\) \+ ' expanded'/);
assert.match(script, /data-expand-mode="callers"/);
assert.match(script, /data-expand-mode="all"/);
assert.match(script, /function expandAllFromNode/);
assert.match(script, /\['callers', 'callees', 'impact'\]\.forEach/);
assert.match(script, />Callees</);
assert.match(script, />Impact</);
assert.match(script, /detail-primary-actions/);
assert.match(script, /copyNodeLocation/);
assert.match(script, /webviewIcon\('external', 'graph-icon'\)/);
assert.match(script, /shape: 'dot'/);
assert.doesNotMatch(script, /function nodeShape/);
assert.doesNotMatch(script, /shape: nodeShape\(node\)/);
assert.match(script, /function fitNetwork/);
assert.match(script, /function exportGraphPng/);
assert.match(script, /function exportGraphJson/);
assert.match(script, /function copyGraphMarkdown/);
assert.match(script, /function graphPngDataUrl/);
assert.match(script, /function graphExportData/);
assert.match(script, /function graphMarkdownSummary/);
assert.match(script, /function exportFileName/);
assert.match(script, /function exportSubtitle/);
assert.match(script, /function slug/);
assert.match(script, /els\.exportPng\.addEventListener\('click', exportGraphPng\)/);
assert.match(script, /els\.exportJson\.addEventListener\('click', exportGraphJson\)/);
assert.match(script, /els\.copyMarkdown\.addEventListener\('click', copyGraphMarkdown\)/);
assert.match(script, /els\.stepLimitDown\.addEventListener\('click', collapseGraphLimit\)/);
assert.match(script, /els\.toggleClusters\.addEventListener\('click', \(\) => setClusterOverlayOpen\(!state\.clusterOverlayOpen\)\)/);
assert.match(script, /document\.querySelectorAll\('\.advanced-controls\[open\], \.action-menu\[open\]'\)/);
assert.match(script, /function setClusterOverlayOpen/);
assert.match(script, /function updateClusterButton/);
assert.match(script, /function updateLimitDownButton/);
assert.match(script, /els\.toggleHelp\.addEventListener\('click', \(\) => setHelpOpen\(true\)\)/);
assert.match(script, /els\.closeHelp\.addEventListener\('click', \(\) => setHelpOpen\(false\)\)/);
assert.match(script, /event\.key === '\?'/);
assert.match(script, /function setHelpOpen/);
assert.match(script, /help-open/);
assert.match(script, /querySelector\('canvas'\)/);
assert.match(script, /getViewPosition\(\)/);
assert.match(script, /state\.network\.fit\(\{ animation: false \}\)/);
assert.match(script, /state\.network\.moveTo\(\{ position: view\.position, scale: view\.scale, animation: false \}\)/);
assert.match(script, /toDataURL\('image\/png'\)/);
assert.match(script, /type: 'saveGraphPng', dataUrl, fileName: exportFileName\(\)/);
assert.match(script, /type: 'saveGraphJson', data: graphExportData\(\), fileName: exportFileName\('json'\)/);
assert.match(script, /schema: 'codegraph\.graph\.export\.v1'/);
assert.match(script, /state\.network \? state\.network\.getPositions\(\) : \{\}/);
assert.match(script, /nodes: state\.graph\.nodes\.map/);
assert.match(script, /edges: state\.graph\.edges\.map/);
assert.match(script, /Preparing JSON export/);
assert.match(script, /message\.type === 'exportResult'/);
assert.match(script, /function exportResultLabel/);
assert.match(script, /Exported ' \+ exportResultLabel\(message\.format\)/);
assert.match(script, /Preparing PNG export/);
assert.match(script, /function animationOptions/);
assert.match(script, /function showHoverTip/);
assert.match(script, /function hideHoverTip/);
assert.match(script, /function updateMotionButton/);
assert.match(script, /function updateOrbitButton/);
assert.match(script, /function setButtonContent/);
assert.match(script, /button\.innerHTML = '<span>' \+ webviewIcon\(iconName, 'graph-icon'\) \+ '<\/span>' \+ escapeHtml\(label\)/);
assert.match(script, /button\.innerHTML = webviewIcon\(iconName, 'graph-icon'\)/);
assert.match(script, /function updateFocusButton/);
assert.match(script, /function updateControlsButton/);
assert.match(script, /function setControlsOpen/);
assert.match(script, /function updateDetailsButton/);
assert.match(script, /function updateLegendButton/);
assert.match(script, /function updateMiniMapButton/);
assert.match(script, /function updateGraphStats/);
assert.match(script, /function renderGraphModeBar/);
assert.match(script, /function modeBarActions/);
assert.match(script, /if \(!active\.length\) \{/);
assert.match(script, /\+\' \+ overflowCount\.toLocaleString\(\) \+ \' above/);
assert.match(script, /els\.graphModeBar\.addEventListener\('click'/);
assert.match(script, /data-view-action/);
assert.match(script, /function setDetailsOpen/);
assert.match(script, /function setLegendOpen/);
assert.match(script, /function setMiniMapOpen/);
assert.match(script, /function closeAdvancedControls/);
assert.match(script, /document\.querySelectorAll\('\.action-menu\[open\]'\)/);
assert.match(script, /function isTypingTarget/);
assert.match(script, /prefers-reduced-motion/);
assert.match(script, /stabilize/);
assert.match(script, /stabilizationProgress/);
assert.match(script, /stabilized/);
assert.match(script, /hoverNode/);
assert.match(script, /doubleClick/);
assert.match(script, /deselectNode[\s\S]*updateFocusButton/);
assert.match(script, /event\.key === 'Escape'/);
assert.match(script, /event\.key === '\//);
assert.match(script, /event\.key === 'Enter'/);
assert.match(script, /canOpenNode\(selected\)/);
assert.match(script, /state\.orbit/);
assert.match(script, /state\.focusOnly/);
assert.match(script, /state\.detailsOpen/);
assert.match(script, /state\.controlsOpen/);
assert.match(script, /state\.legendOpen/);
assert.match(script, /state\.miniMapOpen/);
assert.match(script, /depthMode/);
assert.match(script, /spacingMode/);
assert.match(script, /labelMode/);
assert.match(script, /filePattern/);
assert.match(script, /pattern: els\.filePattern\.value\.trim\(\)/);
assert.match(script, /seed\.pattern/);
assert.match(script, /Stabilize/);
assert.match(script, /id="centerNode"/);
assert.match(script, />Center</);
assert.match(script, /id="copyNodeLocation"/);
assert.match(script, /id="openSource"/);
assert.match(script, /class="detail-primary-actions"/);
assert.match(script, /class="detail-actions"/);
assert.match(script, /class="detail-table"/);
assert.match(script, /class="neighbor-table"/);
assert.match(script, /id="prevNeighbors"/);
assert.match(script, /id="nextNeighbors"/);
assert.match(script, /Raw Codegraph payload/);
assert.match(script, /dragEnd/);
assert.match(script, /scheduleClusterOverlayRender\(true\)/);
assert.match(script, /scheduleClusterOverlayRender\(\)/);
assert.match(script, /openResult/);
assert.match(script, /function canOpenNode/);

assert.match(styles, /\.graph-network/);
assert.match(styles, /\.cluster-overlay/);
assert.match(styles, /\.cluster-hull/);
assert.match(styles, /\.cluster-fill/);
assert.match(styles, /\.cluster-hull\.active \.cluster-fill/);
assert.match(styles, /pointer-events: stroke/);
assert.match(styles, /\.cluster-label/);
assert.match(styles, /\.cluster-return/);
assert.match(styles, /\.loading-label::before/);
assert.match(styles, /@keyframes graph-spin/);
assert.match(styles, /\.graph-network canvas/);
assert.match(styles, /\.graph-insight/);
assert.match(styles, /\.insight-chip/);
assert.match(styles, /\.insight-chip\.strong/);
assert.match(styles, /\.insight-chip\.warning/);
assert.match(styles, /\.insight-action/);
assert.match(styles, /\.title-row/);
assert.match(styles, /\.topbar-meta/);
assert.match(styles, /\.index-freshness/);
assert.match(styles, /\.index-freshness\.fresh/);
assert.match(styles, /\.index-freshness\.stale/);
assert.match(styles, /\.activity-strip/);
assert.match(styles, /\.activity-strip\.cached/);
assert.match(styles, /\.activity-strip\.loading/);
assert.match(styles, /\.activity-refresh/);
assert.match(styles, /\.graph-icon/);
assert.match(styles, /\.panel-toggle/);
assert.match(styles, /body\.controls-collapsed \.controls/);
assert.match(styles, /\.activity-panel/);
assert.match(styles, /\.activity-list/);
assert.match(styles, /\.activity-item/);
assert.match(styles, /\.subtitle::before/);
assert.match(styles, /\.quick-selects/);
assert.match(styles, /\.icon-actions/);
assert.match(styles, /\.icon-button/);
assert.match(styles, /\.action-menu/);
assert.match(styles, /\.menu-button/);
assert.match(styles, /\.action-menu-panel/);
assert.match(styles, /\.menu-action/);
assert.match(styles, /\.shortcut-overlay/);
assert.match(styles, /\.shortcut-grid/);
assert.match(styles, /\.state-card/);
assert.match(styles, /\.state-actions/);
assert.match(styles, /\.state-card\.loading::before/);
assert.match(styles, /\.advanced-controls/);
assert.match(styles, /\.advanced-panel/);
assert.match(styles, /\.advanced-panel input/);
assert.match(styles, /\.detail-primary-actions/);
assert.match(styles, /body\.details-open/);
assert.match(styles, /minmax\(300px, clamp\(300px, 26vw, 480px\)\)/);
assert.match(styles, /container-type: inline-size/);
assert.match(styles, /@container \(max-width: 420px\)/);
assert.match(styles, /@media \(max-width: 1180px\)/);
assert.match(styles, /body\.legend-open/);
assert.match(styles, /body\.mini-map-open/);
assert.match(styles, /\.graph-hud/);
assert.match(styles, /\.graph-mode-bar/);
assert.match(styles, /\.mode-actions/);
assert.match(styles, /\.mode-overflow/);
assert.match(styles, /\.hover-tip/);
assert.match(styles, /\.mini-map/);
assert.doesNotMatch(styles, /\.edge/);
assert.doesNotMatch(styles, /\.node \.halo/);
assert.doesNotMatch(styles, /edge-flow/);
assert.match(styles, /\.neighbor-list/);
assert.match(styles, /\.neighbor-table/);
assert.match(styles, /\.neighbor-table td[\s\S]*white-space: normal/);
assert.match(styles, /\.neighbor-status/);
assert.match(styles, /\.topbar-meta[\s\S]*flex-wrap: wrap/);
assert.match(styles, /\.icon-actions[\s\S]*flex-wrap: wrap/);
assert.match(styles, /\.canvas-wrap[\s\S]*min-height: 520px/);
assert.match(styles, /@media \(max-width: 1180px\)[\s\S]*\.canvas-wrap \{ min-height: 460px; \}/);
assert.match(styles, /@media \(max-width: 920px\)[\s\S]*\.action-menu-panel \{ left: 0; right: auto; \}/);
assert.match(styles, /@media \(max-width: 920px\)[\s\S]*\.canvas-wrap \{ min-height: 420px; \}/);
assert.match(styles, /@media \(max-width: 560px\)[\s\S]*\.canvas-wrap \{ min-height: 380px; \}/);
assert.match(styles, /\.cluster-return[\s\S]*minmax\(112px, auto\)/);
assert.match(styles, /\.detail-table,[\s\S]*\.neighbor-table[\s\S]*table-layout: fixed/);
assert.match(styles, /width: clamp\(64px, 30%, 92px\)/);
assert.match(styles, /\.group-action[\s\S]*overflow-wrap: anywhere/);
assert.match(styles, /\.detail-actions/);
assert.match(styles, /\.detail-actions \.group-action/);
assert.match(styles, /\.detail-table/);
assert.match(styles, /\.detail-head/);
assert.doesNotMatch(styles, /halo-pulse/);
assert.match(styles, /\.details/);
assert.match(styles, /\.raw-payload/);

assert.match(graphPanelSource, /saveGraphPng/);
assert.match(graphPanelSource, /saveGraphJson/);
assert.match(graphPanelSource, /cache = new Map/);
assert.match(graphPanelSource, /indexUpdatedAt/);
assert.match(graphPanelSource, /getCodegraphIndexUpdatedAt/);
assert.match(graphPanelSource, /codegraph\.db/);
assert.match(graphPanelSource, /createFileSystemWatcher/);
assert.match(graphPanelSource, /RelativePattern/);
assert.match(graphPanelSource, /cache\.clear\(\)/);
assert.match(graphPanelSource, /type: "indexChanged"/);
assert.match(graphPanelSource, /disposeIndexWatcher/);
assert.match(graphPanelSource, /message\.force/);
assert.match(graphPanelSource, /loadFiles\(filter, pattern, force\)/);
assert.match(graphPanelSource, /cached && !force/);
assert.match(graphPanelSource, /cached && !message\.force/);
assert.match(graphPanelSource, /Refreshing indexed files/);
assert.match(graphPanelSource, /webviewReady = false/);
assert.match(graphPanelSource, /lastAutoLoadKey = ""/);
assert.match(graphPanelSource, /onDidReceiveMessage[\s\S]*webview\.html = .*getGraphHtml/);
assert.match(graphPanelSource, /await this\.autoLoadInitialFiles\(\)/);
assert.match(graphPanelSource, /this\.webviewReady = true/);
assert.match(graphPanelSource, /graphCacheKey\("initial-files", this\.state\.workspacePath\)/);
assert.match(graphPanelSource, /normalizePositiveNumber\(seed\.limit, 20\)/);
assert.match(graphPanelSource, /graphCacheKey/);
assert.match(graphPanelSource, /type: "loading"/);
assert.match(graphPanelSource, /graphRequestId/);
assert.match(graphPanelSource, /requestId !== this\.graphRequestId/);
assert.match(graphPanelSource, /cached: true/);
assert.match(graphPanelSource, /expandNode/);
assert.match(graphPanelSource, /expandedNode/);
assert.match(graphPanelSource, /clearCodegraphCache/);
assert.match(graphPanelSource, /graphRequestId: message\.graphRequestId/);
assert.match(graphPanelSource, /getCodegraphCallers/);
assert.match(graphPanelSource, /getCodegraphCallees/);
assert.match(graphPanelSource, /getCodegraphImpact/);
assert.match(graphPanelSource, /showSaveDialog/);
assert.match(graphPanelSource, /workspace\.fs\.writeFile/);
assert.match(graphPanelSource, /Buffer\.from/);
assert.match(graphPanelSource, /Buffer\.from\(content, "utf8"\)/);
assert.match(graphPanelSource, /data:image\\\/png;base64/);
assert.match(graphPanelSource, /toSafePngFileName/);
assert.match(graphPanelSource, /toSafeFileName/);
assert.match(graphPanelSource, /Export Codegraph graph data as JSON/);
assert.match(graphPanelSource, /exportResult/);
assert.match(graphPanelSource, /format: "png"/);
assert.match(graphPanelSource, /format: "json"/);
assert.match(graphPanelSource, /function showCodegraphDocument/);
assert.match(graphPanelSource, /viewColumn: vscode\.ViewColumn\.Beside/);

console.log("graphAssets tests passed");
